### ISSUE TITLE
Release todo:

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/CryoEngines#59]
- [x] Fix smokePoint for all engines
- [ ] Verify Stromboli, Fuji boattails for gimbal clearance
- [ ] FX for CryoEnginesRestock
- [x] Balance numbers for CryoEnginesRestock
- [x] Balance numbers for CryoEnginesLFO
